/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.khanh.clothingshopsalemanagement.view;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import lombok.Getter;
import me.khanh.clothingshopsalemanagement.view.panel.LoginPanel;

/**
 *
 * @author ADMIN
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Getter for the loading label component.
     *
     * @return the loading label component
     */
    @Getter
    private JLabel loadingLabel;

    /**
     * Constructor for the MainFrame class. Initializes the main window with the
     * application title, location, and content pane.
     *
     * The window is set to be non-resizable.
     */
    public MainFrame() {
        initComponents();

        setResizable(false);
        setTitle("Clothing Shop Sale Management");
        setLocation(500, 100);
//        setLocationByPlatform(true);

//        LoginPanel panel = new LoginPanel(this);
        addLoadingGif();

        LoginPanel panel = new LoginPanel(this);
        setContentPane(panel);
        pack();
    }

    /**
     * Adds a loading GIF to the center of the window.
     */
    public final void addLoadingGif() {
        ImageIcon loadingGif = new ImageIcon(getClass().getResource("/loading.gif"));
        loadingLabel = new JLabel(loadingGif);
        int labelWidth = loadingLabel.getPreferredSize().width;
        int labelHeight = loadingLabel.getPreferredSize().height;

        int x = (getWidth() - labelWidth) / 2;
        int y = (getHeight() - labelHeight) / 2;

        loadingLabel.setBounds(x, y, labelWidth, labelHeight);
        add(loadingLabel);
        loadingLabel.setVisible(false);
    }

    /**
     * Removes the loading GIF from the window.
     */
    public final void removeLoadingGif() {
        remove(loadingLabel);
    }

    /**
     * Displays the loading GIF.
     */
    public void showLoading() {
        loadingLabel.setVisible(true);
    }

    /**
     * Hides the loading GIF.
     */
    public void hideLoading() {
        loadingLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
