/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package me.khanh.clothingshopsalemanagement.view.panel.product;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import lombok.Getter;
import me.khanh.clothingshopsalemanagement.model.product.Gender;
import me.khanh.clothingshopsalemanagement.model.product.Product;
import me.khanh.clothingshopsalemanagement.util.ImageUtil;
import me.khanh.clothingshopsalemanagement.view.panel.ProductManagement;

/**
 *
 * @author ADMIN
 */
public class EditProductPanel extends javax.swing.JPanel {

    @Getter
    private final JDialog parent;
    @Getter
    private final ProductManagement management;
    @Getter
    private final Product product;

    private JTextField lastInvalidField;
    private Border lastInvalidFiledBorder;
    private ImageIcon image;
    private boolean imageModified = false;

    private final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyy HH:mm:ss");

    /**
     * Creates new form EditProductPanel
     *
     * @param parent
     * @param management
     * @param product
     */
    public EditProductPanel(JDialog parent, ProductManagement management, Product product) {
        initComponents();
        this.parent = parent;
        this.management = management;
        this.product = product;

        management.getProductDAO().getManager().getImageDAO().get(product.getImageId()).thenAccept((icon) -> {
            if (icon.isPresent()) {
                ImageIcon resizedIcon = ImageUtil.resize(icon.get(), 150, 170);
                productImage.setIcon(resizedIcon);
                image = resizedIcon;
            } else {
                ImageIcon imageHolder = new ImageIcon(getClass().getResource("/no-picture.png"));
                productImage.setIcon(ImageUtil.resize(imageHolder, 150, 170));
            }
        }).join();

        name.setText(product.getName());
        price.setText(String.valueOf(product.getPrice()));
        stock.setText(String.valueOf(product.getStock()));
        brand.setText(product.getBrand());
        size.setText(product.getSize());
        color.setText(product.getColor());
        gender.setSelectedItem(product.getGender().getValue());
        description.setText(product.getDescription());

        addedByLabel.setText("Added By: " + product.getAddedBy());
        addedDateLabel.setText("Added Date: " + DATE_FORMAT.format(product.getAddedDate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productImage = new javax.swing.JLabel();
        size = new javax.swing.JTextField();
        descriptionScrollPane = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        colroLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        nameScrollPane = new javax.swing.JScrollPane();
        name = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        changeImageButton = new javax.swing.JButton();
        genderLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        stockLabel = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        addedByLabel = new javax.swing.JLabel();
        addedDateLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 161, 244)));

        productImage.setPreferredSize(new java.awt.Dimension(128, 128));

        description.setColumns(20);
        description.setRows(5);
        descriptionScrollPane.setViewportView(description);

        colroLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        colroLabel.setText("Color");

        saveButton.setBackground(new java.awt.Color(38, 161, 244));
        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(250, 255, 248));
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        nameScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        nameScrollPane.setViewportView(name);

        changeImageButton.setBackground(new java.awt.Color(101, 101, 101));
        changeImageButton.setForeground(new java.awt.Color(221, 221, 221));
        changeImageButton.setText("Change Image");
        changeImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeImageButtonActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderLabel.setText("Gender");

        priceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceLabel.setText("Price");

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unisex", "Male", "Female" }));

        stockLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stockLabel.setText("Stock");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Brand");

        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionLabel.setText("Description");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLabel.setText("Name");

        sizeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sizeLabel.setText("Size");

        addedByLabel.setText("Added By: {added_by}");

        addedDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addedDateLabel.setText("Added Date: {added_date}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(productImage, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(changeImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(46, 46, 46)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(stockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(nameScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descriptionScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(descriptionLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(addedByLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addedDateLabel)))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stockLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sizeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(productImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colroLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(changeImageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addedByLabel)
                    .addComponent(addedDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changeImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeImageButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(management.getPanel().getMainFrame());
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                image = new ImageIcon(ImageIO.read(selectedFile));
                productImage.setIcon(ImageUtil.resize(image, 150, 170));
                imageModified = true;
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(management.getPanel().getMainFrame(), "Error loading image: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_changeImageButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (lastInvalidField != null && lastInvalidFiledBorder != null) {
            lastInvalidField.setBorder(lastInvalidFiledBorder);
        }

        if (isBlank(name, "name")) {
            return;
        }

        if (isBlank(price, "price")) {
            return;
        }

        if (isBlank(stock, "stock")) {
            return;
        }

        if (isBlank(brand, "brand")) {
            return;
        }

        if (isBlank(size, "size")) {
            return;
        }

        if (isBlank(color, "color")) {
            return;
        }

        double productPrice;
        try {
            productPrice = Double.parseDouble(price.getText());

        } catch (NumberFormatException e) {
            lastInvalidField = price;
            lastInvalidFiledBorder = price.getBorder();
            LineBorder errorBorder = new LineBorder(Color.RED, 2);
            price.setBorder(errorBorder);
            JOptionPane.showMessageDialog(
                    this,
                    String.format("%s is invalid price!", price.getText()),
                    "WARNING",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int productStock;
        try {
            productStock = Integer.parseInt(stock.getText());
        } catch (NumberFormatException e) {
            lastInvalidField = stock;
            lastInvalidFiledBorder = stock.getBorder();
            LineBorder errorBorder = new LineBorder(Color.RED, 2);
            stock.setBorder(errorBorder);
            JOptionPane.showMessageDialog(
                    this,
                    String.format("%s is invalid stock number!", stock.getText()),
                    "WARNING",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int imageId = product.getImageId();
        if (imageModified) {
            imageId = management.getProductDAO().getManager().getImageDAO().save(image).join();
        }

        product.setName(name.getText());
        product.setDescription(description.getText());
        product.setPrice(productPrice);
        product.setStock(productStock);
        product.setBrand(brand.getText());
        product.setSize(size.getText());
        product.setColor(color.getText());
        product.setImageId(imageId);
        product.setGender(Gender.valueOf(((String) gender.getSelectedItem()).toUpperCase()));

        management.getProductDAO().update(product).thenRun(() -> {
            JOptionPane.showMessageDialog(
                    this,
                    "Edited product successfully. Product ID: " + product.getId(),
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            parent.dispose();
            management.updateProducts();
        });
    }//GEN-LAST:event_saveButtonActionPerformed

    private boolean isBlank(JTextField textField, String field) {
        LineBorder errorBorder = new LineBorder(Color.RED, 2);
        if (textField.getText() == null || textField.getText().isBlank()) {
            lastInvalidField = textField;
            lastInvalidFiledBorder = textField.getBorder();
            textField.setBorder(errorBorder);
            JOptionPane.showMessageDialog(
                    this,
                    String.format("Product %s cannot be blank!", field),
                    "WARNING",
                    JOptionPane.WARNING_MESSAGE);
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addedByLabel;
    private javax.swing.JLabel addedDateLabel;
    private javax.swing.JTextField brand;
    private javax.swing.JButton changeImageButton;
    private javax.swing.JTextField color;
    private javax.swing.JLabel colroLabel;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JScrollPane nameScrollPane;
    private javax.swing.JTextField price;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel productImage;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField size;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTextField stock;
    private javax.swing.JLabel stockLabel;
    // End of variables declaration//GEN-END:variables
}
