/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package me.khanh.clothingshopsalemanagement.view.panel;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import lombok.Getter;
import me.khanh.clothingshopsalemanagement.model.ClothingShopSaleManagement;
import me.khanh.clothingshopsalemanagement.model.authentication.User;
import me.khanh.clothingshopsalemanagement.model.authentication.UserDAO;
import me.khanh.clothingshopsalemanagement.util.HashUtil;
import me.khanh.clothingshopsalemanagement.view.MainFrame;

/**
 *
 * @author ADMIN
 */
public class LoginPanel extends javax.swing.JPanel {

    @Getter
    private final MainFrame mainFrame;

    private boolean showHintUsername = true;
    private boolean showHintPassword = true;
    private JTextField lastInvalidField;
    private Border lastInvalidFiledBorder;
    private final LineBorder errorBorder = new LineBorder(Color.RED, 2);

    /**
     * Creates new form BetterLoginPanel
     *
     * @param mainFrame MainFrame
     */
    public LoginPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
         
        removeFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        accountIcon = new javax.swing.JLabel();
        usernmaeField = new javax.swing.JTextField();
        lockIcon = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        passwordVisibilityButton = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop.png"))); // NOI18N

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(49, 84, 181));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");

        accountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N

        usernmaeField.setText("Username");
        usernmaeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernmaeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernmaeFieldFocusLost(evt);
            }
        });

        lockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock.png"))); // NOI18N

        passwordField.setText("Password");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(244, 97, 56));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 251, 237));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passwordVisibilityButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invisible.png"))); // NOI18N
        passwordVisibilityButton.setBorder(null);
        passwordVisibilityButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/visible.png"))); // NOI18N
        passwordVisibilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordVisibilityButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lockIcon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(passwordVisibilityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(accountIcon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(usernmaeField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(10, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernmaeField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountIcon))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordVisibilityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lockIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField))
                .addGap(33, 33, 33)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernmaeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernmaeFieldFocusGained
        if (showHintUsername) {
            usernmaeField.setText("");
            usernmaeField.setForeground(Color.BLACK);
            showHintUsername = false;
        }
    }//GEN-LAST:event_usernmaeFieldFocusGained

    private void usernmaeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernmaeFieldFocusLost
        if (usernmaeField.getText().isEmpty()) {
            usernmaeField.setForeground(Color.GRAY);
            usernmaeField.setText("Username");
            showHintUsername = true;
        }
    }//GEN-LAST:event_usernmaeFieldFocusLost

    private void passwordVisibilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordVisibilityButtonActionPerformed
        if (passwordVisibilityButton.isSelected()) {
            passwordVisibilityButton.setBackground(Color.WHITE);
            passwordField.setEchoChar((char) 0);
        } else {
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordVisibilityButtonActionPerformed

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (showHintPassword) {
            passwordField.setText("");
            passwordField.setForeground(Color.BLACK);
            showHintPassword = false;
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        String password = new String(passwordField.getPassword());
        if (password.isEmpty()) {
            passwordField.setForeground(Color.GRAY);
            passwordField.setText("Password");
            showHintPassword = true;
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            handleLoginRequest();
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if (lastInvalidField != null && lastInvalidFiledBorder != null) {
            lastInvalidField.setBorder(lastInvalidFiledBorder);
        }
        
        if (showHintUsername) {
            setErrorBorder(usernmaeField);
            JOptionPane.showMessageDialog(
                    this,
                    "Please input username",
                    "WARNING",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (showHintPassword) {
            setErrorBorder(passwordField);
            JOptionPane.showMessageDialog(
                    this,
                    "Please input password",
                    "WARNING",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        handleLoginRequest();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void removeFocus() {
        usernmaeField.setFocusable(false);
        passwordField.setFocusable(false);
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                usernmaeField.setFocusable(true);
                passwordField.setFocusable(true);
            }
        }, 1000);
    }

    /**
     * Handles the login request when the login button is clicked.
     */
    private void handleLoginRequest() {
        String username = usernmaeField.getText();
        if (username == null || username.isBlank()) {
            JOptionPane.showMessageDialog(this, "Invalid username", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        mainFrame.showLoading();

        UserDAO userdao = ClothingShopSaleManagement.getInstance().getDAOManager().getUserDAO();

        userdao.get(username).thenAccept((optionalUser) -> {
            mainFrame.hideLoading();

            if (optionalUser.isEmpty()) {
                setErrorBorder(usernmaeField);
                JOptionPane.showMessageDialog(
                        this,
                        String.format("User `%s` does not exist", username),
                        "WARNING",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            User user = optionalUser.get();

            String password = new String(passwordField.getPassword());
            if (!password.isBlank() && HashUtil.hash(password).equals(user.getHashedPassword())) {
                mainFrame.setSize(848, 520);
                mainFrame.setContentPane(new DashboardPanel(mainFrame, user));
                SwingUtilities.updateComponentTreeUI(mainFrame);
                mainFrame.addLoadingGif();
            } else {
                setErrorBorder(passwordField);
                JOptionPane.showMessageDialog(
                        this,
                        String.format("Wrong password for user %s", username),
                        "WARNING",
                        JOptionPane.WARNING_MESSAGE);
            }
        });
    }
    
    public void setErrorBorder(JTextField field) {
        lastInvalidField = field;
        lastInvalidFiledBorder = field.getBorder();
        field.setBorder(errorBorder);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountIcon;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel lockIcon;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JToggleButton passwordVisibilityButton;
    private javax.swing.JTextField usernmaeField;
    // End of variables declaration//GEN-END:variables
}
